# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 하이욤
email: smj880829@nate.com
description: JUN의 페이지
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://smj880829.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  smj880829
encoding: utf-8

# Build settings
markdown: kramdown
